plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - - "@semantic-release/exec"
    - prepareCmd: "./prepare-release.sh ${nextRelease.version}"
  - - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
        - "extension.yaml"
        - "CHANGELOG.md"
        - "README.md"
      message: "chore(release): prepare ${nextRelease.version} [skip ci]"

branches:
  - name: "main"

tagFormat: ${version}
